spring.application.name=account-service

# --- Datasource ---
spring.datasource.url=
spring.datasource.driver-class-name=
spring.jpa.database-platform=
spring.jpa.hibernate.ddl-auto=

# --- H2 Console (local only) ---
spring.h2.console.enabled=false
